# Generated by Django 3.2 on 2023-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0001_initial'),
        ('recipes', '0006_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                related_name='tags', to='tags.Tag', verbose_name='Теги'
            ),
        ),
    ]
